### ISSUE TITLE
Unauthorized license change

### ISSUE THREAD

**Issue by Daja177** [shoui520/shoui520.github.io#26]
In the commit 80139acfeb45df8000bcf71a3e5ca7fb82ec5026, the repository which was previously licensed under GNU General Public License Version 3 (GPLv3) has been switched to Creative Commons Attribution-NonCommercial-NoDerivatives (CC BY-NC-ND) without obtaining consent from the previous contributors. This action violates the rights of the contributors as granted by the original license, as the GPLv3 license provides no permission to license the work in any other way.

To rectify this issue and ensure a proper procedure for license changes, I kindly request the following actions:
1. Revert the repository's license back to the original GPLv3 or a compatible open-source license.
2. If a license change is desired, please engage in a respectful and inclusive process. Contact the previous contributors to request their permission for the license change. In the event that permission is not granted, it will be necessary to discuss options to address their contributions appropriately, which may involve reverting their contributions.

Taking these steps will uphold the rights of the contributors and ensure that license changes are conducted in a lawful and collaborative manner.

**Comment by shoui520** [comment]
Hello,

You are right, thanks for letting me know. The license has been reverted to GPLv3.

**Comment by Daja177** [comment]
Thank you for promptly addressing the license issue!

I value the principles of openness and freedom associated with GPL licenses, particularly the rights to share and modify. As a contributor to the site, I'm happy to support a license change that aligns with these values so long as a proper discussion is held.
