### ISSUE TITLE
light novel section

### ISSUE THREAD

**Issue by KonstantinDjairo** [shoui520/shoui520.github.io#41]
hi, im currently seeding a massive (100gb+) collection of light novels in epub format
could you add it in your recommendations of resources for reading?
> https://nyaa.si/?f=0&c=0_0&q=TMW
> https://nyaa.si/view/1548943

**Comment by brishtibheja** [comment]
How many are there and what is the source of it? Is it commonly available on LibGen and other shadow libraries?
